#!/usr/bin/env python3

import argparse
import sys
import csv


def get_arg_parser():
  parser = argparse.ArgumentParser(
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)

  parser.add_argument(
    "path", help="The path to the csv file to extract from.")

  parser.add_argument(
    "column", nargs="?", type=int, default=0, help="The column to extract")

  return parser


def main(argv):
  opts = get_arg_parser().parse_args(argv[1:])
  c = opts.column
  with open(opts.path, "r") as f:
    reader = csv.reader(f)
    for record in reader:
      print(record[c])


if __name__ == "__main__":
  main(sys.argv)
