#!/usr/bin/env python3

import sys
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


if __name__ == '__main__':
    data = pd.read_csv(sys.argv[1])
    x_col = sys.argv[2] if len(sys.argv) > 2 else None
    y_cols = sys.argv[3:]
    if y_cols:
        for y_col in y_cols:
            data.plot(x=x_col, y = y_col)
    else:
        data.plot(x=x_col)
    plt.show()
