#!/bin/sh
export ARCHSTRING=" "
if [[ "$1" == *cache* ]]; then
	export ARCHSTRING=:"$ARCHSTRING --cachedebugfile cache.log"
fi

SIM_PATH=/local/ssd/dev/arch/bin/sim
if [[ "$1" == *debug* ]]; then 
   SIM_BIN="gdb --args $SIM_PATH"
elif [[ "$1" == *valgrind* ]]; then
   SIM_BIN="valgrind --tool=cachegrind $SIM_PATH"
else
   SIM_BIN="$SIM_PATH"
fi

$SIM_BIN --timing --quiet --uarchtrace_print_tag_info 1 --uarchtrace utrace.log --l2cachetrace l2trace.log *.exe
#$SIM_BIN --timing --quiet *.exe
#$SIM_BIN --quiet *.exe


# Do some common analysis every time
/prj/dsp/qdsp6/arch/v60/mtools/v60_latest/gnu/bin/hexagon-objdump -d *.exe > asm.s &
