#!/bin/bash
export ARCHSTRING=" "
MOREARGS=" "
SIM_PATH=$Q6SIM

REV="--core V60A_512"

if [[ "$1" == *cache* ]]; then
	export ARCHSTRING=:"$ARCHSTRING --cachedebugfile cache.log"
fi

if [[ "$1" == *debug* ]]; then 
   SIM_BIN="gdb --args $SIM_PATH"
elif [[ "$1" == *cachgrind* ]]; then
   SIM_BIN="valgrind --tool=cachegrind $SIM_PATH"
elif [[ "$1" == *memcheck* ]]; then
   VGDB="--vgdb=yes --vgdb-error=0"
   SIM_BIN="valgrind --tool=memcheck --leak-check=yes -v --track-origins=yes $SIM_PATH"
else
   SIM_BIN="$SIM_PATH"
fi

if [[ "$1" == *hexgdb* ]]; then
   MOREARGS="--interactive $MOREARGS"
fi

if [[ "$1" != *notiming* ]]; then
   MOREARGS="--timing $MOREARGS"
fi

RUN_EXEC="$SIM_BIN $MOREARGS $REV --quiet "

$RUN_EXEC --magic_angel --uarchtrace utrace.log --uarchtrace_print_l2sb_info 1 --uarchtrace_print_stall_info 1 *.exe
#$RUN_EXEC --coproctrace coproc.log *.exe
#$RUN_EXEC --pctrace pctrace.log *.exe
#$RUN_EXEC --stalltrace stalltrace.log *.exe
#$RUN_EXEC *.exe

RETVAL=$?

# Do some common analysis every time
/prj/dsp/qdsp6/arch/v60/mtools/v60_latest/gnu/bin/hexagon-objdump -d *.exe > asm.s &

exit $RETVAL
