#!/bin/sh
export ARCHSTRING=" "
MOREARGS=" "
SIM_PATH=/local/ssd/dev/arch/bin/sim

REV="--core V60A_512"

if [[ "$1" == *cache* ]]; then
	export ARCHSTRING=:"$ARCHSTRING --cachedebugfile cache.log"
fi

if [[ "$1" == *debug* ]]; then 
   SIM_BIN="gdb --args $SIM_PATH"
elif [[ "$1" == *valgrind* ]]; then
   SIM_BIN="valgrind --tool=cachegrind $SIM_PATH"
else
   SIM_BIN="$SIM_PATH"
fi

if [[ "$1" == *hexgdb* ]]; then
   MOREARGS="--interactive $MOREARGS"
fi

if [[ "$1" != *notiming* ]]; then
   MOREARGS="--timing $MOREARGS"
fi

$SIM_BIN $MOREARGS $REV --quiet --uarchtrace utrace.log *.exe
#$SIM_BIN $MOREARGS $REV --quiet *.exe


# Do some common analysis every time
/prj/dsp/qdsp6/arch/v60/mtools/v60_latest/gnu/bin/hexagon-objdump -d *.exe > asm.s &
