#!/usr/bin/env python3
import http.server
import ssl
import sys

certfile_path = sys.argv[1] if len(sys.argv) > 1 else './server.pem'
print(certfile_path)

httpd = http.server.HTTPServer(('localhost', 4443),
                               http.server.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket(
    httpd.socket,
    certfile=certfile_path,
    keyfile=certfile_path.replace('.pem', '.key'),
    server_side=True)
httpd.serve_forever()
